### ISSUE TITLE
Accidental video download

### ISSUE THREAD

**Issue by Lechindianer** [sunya9/beta#460]
**Describe the bug**
Accidental download of a video file when (re)loading beta.

**To Reproduce**
1. Go to your stream (https://beta.pnut.io/) which included a video (alternative see post https://beta.pnut.io/@Andrew/posts/653757)
2. See video file entitled "39-1564994523761.m4v" getting downloaded

**Expected behavior**
The video file without download

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chromium
 - Version 76.0.3809.100

**Comment by 33mhz** [comment]
Presumably Beta is just inserting the HTML from the oembed. Interestingly Firefox plays the video in Beta, instead of downloading it. Likewise, the same behavior works if you visit [the video file](https://d2cpyc5146f7yj.cloudfront.net/P2JPQrzYlupEGh12cvTghV6mEJt2IxlyNpfLfCZQ344.m4v?Expires=1660927920&Signature=XgwgeYeGPy2vRuX4YYLa1FOBPg5B5VQ9XAvHtlquAj5IiPyMmyiwZu2RcfVhwHgxdaWTpI6y4ZqL2Fbh7kwHzT0Dedk66Jdu9zJYdcV7LhMEL1LH3izyMhCf6lQR7dSbC2xzDEGXTnlwmT1Aze3xDFT30PJJ56ytLm6tlwFsAICPtE4V2VviJse-XpNZUPXvza75CDe6EtYzewQsiMWhUCWkMv1UilU-RpFD~p7bdBPw8TWattPTo4kG~wUpZ0zIRmeGcepaoFVvf17NkAzcw3FF2POFQBxDcfum~RPoZOHGn9964XWiQFV5Nc9FxClMocPCVJioRffR5CThZ8Ffaw__&Key-Pair-Id=APKAJ2QIHBMHH2ICWRYA) directly; FF plays it, Chromium and Chrome download it.

Content-type of the file: `video/quicktime`
Content-disposition: `inline; filename="45-1566319725428.m4v"`

So does Chromium simply not have a codec or understanding of `video/quicktime` or M4V files?

**Comment by 33mhz** [comment]
That seems to be the case. Chromium doesn't recognize `video/quicktime`. This is a short JS browser test that shows some content-types and your browser's support for them: https://videojs.com/mimes.html. `video/quicktime` works in FF, not in Chromium.
